const $=s=>document.querySelector(s);const API=window.INS_CONFIG.apiBase;
const calendarGrid=$('#calendarGrid'),monthLabel=$('#monthLabel'),slotsEl=$('#slots'),slotHeading=$('#slotHeading'),slotHelp=$('#slotHelp');
let viewDate=new Date();viewDate.setDate(1);let selectedDate='',selectedTime='',distanceMiles=null,distanceChargeMiles=null,suggestedLocation=null;
let settings={notarialActFee:10,mileageRate:.76,maxMiles:20,slotMinutes:15};
const fmtMoney=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const prettyDate=s=>s?new Date(`${s}T12:00:00`).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'}):'—';
const prettyTime=t=>{if(!t)return'—';const[h,m]=t.slice(0,5).split(':').map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});};
async function api(action,opts={}){const u=new URL(API);u.searchParams.set('action',action);if(opts.query)for(const[k,v]of Object.entries(opts.query))u.searchParams.set(k,v);const r=await fetch(u,{method:opts.method||'GET',headers:{'Content-Type':'application/json'},body:opts.body?JSON.stringify(opts.body):undefined});let d={};try{d=await r.json();}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d;}
async function loadPublicSettings(){try{const d=await api('settings',{query:{public:'1'}});settings={...settings,...d.settings};updateQuote();}catch{}}
function renderCalendar(){monthLabel.textContent=viewDate.toLocaleDateString('en-US',{month:'long',year:'numeric'});calendarGrid.innerHTML='';const first=new Date(viewDate.getFullYear(),viewDate.getMonth(),1),start=new Date(first);start.setDate(1-first.getDay());const today=new Date();today.setHours(0,0,0,0);for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=dateKey(d),b=document.createElement('button');b.type='button';b.className='day';b.textContent=d.getDate();if(d.getMonth()!==viewDate.getMonth())b.classList.add('other');if(d<today){b.classList.add('past');b.disabled=true;}if(key===dateKey(today))b.classList.add('today');if(key===selectedDate)b.classList.add('selected');if(!b.disabled)b.addEventListener('click',()=>selectDate(key));calendarGrid.appendChild(b);}}
async function selectDate(key){selectedDate=key;selectedTime='';$('#requestedDate').value=key;$('#requestedTime').value='';renderCalendar();updateSummary();slotHeading.textContent=prettyDate(key);slotHelp.textContent='Checking availability…';slotsEl.innerHTML='';try{const d=await api('availability',{query:{date:key}});renderSlots(d.slots||[]);}catch(e){slotHelp.textContent='Availability could not be loaded. Please try again.';slotsEl.innerHTML='';}}
function renderSlots(slots){slotsEl.innerHTML='';if(!slots.length){slotHelp.textContent='No appointment times are available for this date.';return;}slotHelp.textContent='Unavailable times are shown in grey.';slots.forEach(s=>{const b=document.createElement('button');b.type='button';b.className='slot';b.textContent=prettyTime(s.time);b.disabled=!s.available;if(s.time===selectedTime)b.classList.add('selected');if(s.available)b.addEventListener('click',()=>selectTime(s.time));slotsEl.appendChild(b);});}
function selectTime(t){selectedTime=t;$('#requestedTime').value=t;slotsEl.querySelectorAll('.slot').forEach(b=>b.classList.toggle('selected',b.textContent===prettyTime(t)));updateSummary();}
$('#prevMonth').addEventListener('click',()=>{const now=new Date();now.setDate(1);const p=new Date(viewDate);p.setMonth(p.getMonth()-1);if(p>=new Date(now.getFullYear(),now.getMonth(),1)){viewDate=p;renderCalendar();}});$('#nextMonth').addEventListener('click',()=>{viewDate.setMonth(viewDate.getMonth()+1);renderCalendar();});
function updateQuote(){const acts=Math.max(1,Number($('#actCount').value||1)),actCost=acts*Number(settings.notarialActFee||10),miles=distanceChargeMiles==null?0:distanceChargeMiles,travel=miles*Number(settings.mileageRate||.76);$('#summaryActs').textContent=`${acts} × ${fmtMoney(settings.notarialActFee||10)}`;$('#summaryTravel').textContent=distanceChargeMiles==null?'Calculate location':`${distanceMiles.toFixed(1)} mi • ${fmtMoney(travel)}`;$('#summaryTotal').textContent=fmtMoney(actCost+travel);}
function updateSummary(){$('#summaryDate').textContent=prettyDate(selectedDate);$('#summaryTime').textContent=prettyTime(selectedTime);updateQuote();}$('#actCount').addEventListener('input',updateQuote);
function getAddress(){return[$('#address1').value.trim(),$('#city').value.trim(),$('#state').value.trim(),$('#zip').value.trim()].filter(Boolean).join(', ');}function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
$('#distanceBtn').addEventListener('click',async()=>{const out=$('#distanceResult'),destination=getAddress();if(!$('#address1').value.trim()||!$('#city').value.trim()||!$('#zip').value.trim()){out.innerHTML='<div class="notice danger">Enter the street address, city and ZIP code first.</div>';return;}$('#distanceBtn').disabled=true;$('#distanceBtn').textContent='Calculating…';out.innerHTML='';try{const d=await api('distance',{method:'POST',body:{destination}});distanceMiles=Number(d.miles);distanceChargeMiles=Number(d.chargeMiles);suggestedLocation=d.suggested||null;if(d.withinServiceArea){out.innerHTML=`<div class="notice success"><strong>${distanceMiles.toFixed(1)} miles</strong> from the service base. This address is within the service area.</div>`;}else{out.innerHTML=`<div class="notice warning"><strong>${distanceMiles.toFixed(1)} miles</strong> from the service base, beyond the ${settings.maxMiles||20}-mile service area.<br><br><strong>Suggested meeting area:</strong> ${escapeHtml(suggestedLocation?.label||'A point on the route within the service boundary.')}<br><button type="button" class="button secondary compact" id="useSuggestion" style="margin-top:12px">Use suggested meeting area</button></div>`;setTimeout(()=>$('#useSuggestion')?.addEventListener('click',()=>{if(suggestedLocation?.label){$('#address1').value=suggestedLocation.label;$('#city').value=suggestedLocation.city||'';$('#state').value=suggestedLocation.state||'IN';$('#zip').value=suggestedLocation.zip||'';distanceMiles=Number(settings.maxMiles||20);distanceChargeMiles=distanceMiles;suggestedLocation=null;out.innerHTML=`<div class="notice success">Suggested meeting area selected at approximately ${distanceMiles.toFixed(1)} miles.</div>`;updateQuote();}}),0);}updateQuote();}catch(e){out.innerHTML=`<div class="notice danger">${escapeHtml(e.message)} You can still submit the request and the distance can be verified manually.</div>`;distanceMiles=null;distanceChargeMiles=null;updateQuote();}finally{$('#distanceBtn').disabled=false;$('#distanceBtn').textContent='Calculate distance';}});
function validate(){const err=$('#formError');err.textContent='';if(!selectedDate||!selectedTime)return err.textContent='Select an appointment date and time.',false;if(!$('#serviceType').value)return err.textContent='Select a service type.',false;if(!$('#fullName').value.trim()||!$('#phone').value.trim()||!$('#email').value.includes('@'))return err.textContent='Complete your name, phone number and a valid email address.',false;if(!$('#address1').value.trim()||!$('#city').value.trim()||!$('#state').value.trim()||!$('#zip').value.trim())return err.textContent='Complete the meeting address.',false;if(!$('#consent').checked)return err.textContent='Confirm the appointment-request consent.',false;return true;}
$('#submitBooking').addEventListener('click',async()=>{if(!validate())return;const btn=$('#submitBooking');btn.disabled=true;btn.textContent='Submitting…';const acts=Math.max(1,Number($('#actCount').value||1)),chargeMiles=distanceChargeMiles==null?null:Number(distanceChargeMiles),estimatedTotal=acts*Number(settings.notarialActFee||10)+(chargeMiles||0)*Number(settings.mileageRate||.76);const payload={fullName:$('#fullName').value.trim(),phone:$('#phone').value.trim(),email:$('#email').value.trim(),serviceType:$('#serviceType').value,actCount:acts,serviceNotes:$('#serviceNotes').value.trim(),requestedDate:selectedDate,requestedTime:selectedTime,address1:$('#address1').value.trim(),city:$('#city').value.trim(),state:$('#state').value.trim(),zip:$('#zip').value.trim(),distanceMiles,chargeMiles,paymentPreference:$('#paymentPreference').value,estimatedTotal};try{const d=await api('bookings',{method:'POST',body:payload});$('#bookingForm').style.display='none';$('#successScreen').classList.add('active');$('#successReference').textContent=d.reference||'Request submitted';$('#successEmailNote').textContent=d.emailSent?'A request receipt and PDF have been emailed to you.':'Your request is safely stored. Email delivery is not configured yet, so please keep your reference number.';window.scrollTo({top:document.querySelector('.booking-wrap').offsetTop-70,behavior:'smooth'});}catch(e){$('#formError').textContent=e.message;btn.disabled=false;btn.innerHTML='Submit request <span>→</span>';}});
renderCalendar();loadPublicSettings();updateSummary();if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));}
